spring.application.name=hs-tesis

spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.default-models-expand-depth=-1
springdoc.swagger-ui.tagsSorter=alpha

spring.docker.compose.enabled=false
spring.jpa.open-in-view=false

spring.security.user.name=${ADMIN_USERNAME}
spring.security.user.password=${ADMIN_PASSWORD}

minio.url=${MINIO_URL}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket=${MINIO_BUCKET_NAME}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_AMQP_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

spring.jpa.hibernate.naming.physical-strategy=com.hs.hstesis.shared.infrastructure.persistance.jpa.strategy.SnakeCasePhysicalNamingStrategy

ai.service.url=${PYTHON_WORKER_BASE_URL}
ai.service.api-key=${WORKER_API_KEY}