-- Baseline exported from the validated PostgreSQL 16 schema. No local data is included.
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.academic_years (
    id bigint NOT NULL,
    year integer NOT NULL
);

ALTER TABLE public.academic_years ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_years_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.achievement_insights (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    entity_id bigint NOT NULL,
    entity_type character varying(255) NOT NULL,
    insight_text text NOT NULL
);

ALTER TABLE public.achievement_insights ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievement_insights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ai_background_tasks (
    id bigint NOT NULL,
    attempt_count integer NOT NULL,
    available_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    idempotency_key character varying(120) NOT NULL,
    last_error character varying(120),
    status character varying(20) NOT NULL,
    subject_id bigint NOT NULL,
    task_type character varying(40) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT ai_background_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT ai_background_tasks_task_type_check CHECK (((task_type)::text = ANY ((ARRAY['QUESTIONNAIRE_FEEDBACK'::character varying, 'STUDENT_INSIGHT'::character varying])::text[])))
);

ALTER TABLE public.ai_background_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_background_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.areas (
    id bigint NOT NULL,
    coordinator_id bigint,
    name character varying(255) NOT NULL
);

ALTER TABLE public.areas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.areas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    role character varying(50) NOT NULL,
    session_id bigint NOT NULL
);

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chat_sessions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    course_id bigint,
    user_id bigint NOT NULL
);

ALTER TABLE public.chat_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.classrooms (
    id bigint NOT NULL,
    academic_year_id bigint NOT NULL,
    course_id bigint NOT NULL,
    section_id bigint NOT NULL
);

ALTER TABLE public.classrooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classrooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.courses (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    area_id bigint NOT NULL
);

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.document_chunks (
    id bigint NOT NULL,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    page_number integer NOT NULL,
    document_id bigint NOT NULL,
    content_tsv tsvector GENERATED ALWAYS AS (to_tsvector('spanish'::regconfig, COALESCE(content, ''::text))) STORED,
    embedding public.vector(1024)
);

ALTER TABLE public.document_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.document_targets (
    course_id bigint NOT NULL,
    education_level character varying(255) NOT NULL,
    grade_level character varying(255) NOT NULL,
    document_id bigint NOT NULL,
    CONSTRAINT document_targets_education_level_check CHECK (((education_level)::text = 'SECONDARY'::text)),
    CONSTRAINT document_targets_grade_level_check CHECK (((grade_level)::text = 'SECOND'::text))
);

CREATE TABLE public.documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    author_id bigint NOT NULL,
    file_checksum character varying(255) NOT NULL,
    object_key character varying(255) NOT NULL,
    original_file_name character varying(255) NOT NULL,
    format character varying(15) NOT NULL,
    status character varying(15) NOT NULL,
    title character varying(200) NOT NULL,
    topic_id bigint NOT NULL,
    type character varying(15) NOT NULL,
    CONSTRAINT documents_format_check CHECK (((format)::text = 'PDF'::text)),
    CONSTRAINT documents_status_check CHECK (((status)::text = ANY ((ARRAY['UPLOADED'::character varying, 'PROCESSING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT documents_type_check CHECK (((type)::text = 'ACADEMIC'::text))
);

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.enrollments (
    id bigint NOT NULL,
    role_in_classroom character varying(255) NOT NULL,
    user_id bigint,
    classroom_id bigint NOT NULL
);

ALTER TABLE public.enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.grading_periods (
    id bigint NOT NULL,
    bimester character varying(255) NOT NULL,
    end_date date,
    start_date date,
    academic_year_id bigint NOT NULL,
    CONSTRAINT grading_periods_bimester_check CHECK (((bimester)::text = ANY ((ARRAY['FIRST'::character varying, 'SECOND'::character varying, 'THIRD'::character varying, 'FOURTH'::character varying])::text[])))
);

ALTER TABLE public.grading_periods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grading_periods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notification_preferences (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    notify_new_document boolean NOT NULL,
    notify_quiz_results boolean NOT NULL,
    notify_relevant_activity boolean NOT NULL,
    notify_unresolved_quizzes boolean NOT NULL,
    user_id bigint,
    notify_low_performance boolean NOT NULL,
    notify_new_questionnaire boolean NOT NULL,
    notify_new_tutorial boolean NOT NULL
);

ALTER TABLE public.notification_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message character varying(255),
    user_id bigint,
    type character varying(255),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['NEW_QUESTIONNAIRE'::character varying, 'NEW_TUTORIAL'::character varying, 'LOW_PERFORMANCE'::character varying])::text[])))
);

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.onboarding_profiles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed boolean NOT NULL,
    completed_at timestamp(6) without time zone,
    quizzes_completed boolean NOT NULL,
    repository_completed boolean NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.onboarding_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.onboarding_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    permission_name character varying(255) NOT NULL
);

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.platform_tutorials (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(1000) NOT NULL,
    file_url character varying(255) NOT NULL,
    title character varying(255) NOT NULL
);

ALTER TABLE public.platform_tutorials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platform_tutorials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.questionnaire_instances (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    student_id bigint,
    questionnaire_id bigint NOT NULL
);

ALTER TABLE public.questionnaire_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questionnaire_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.questionnaire_submission_answers (
    id bigint NOT NULL,
    is_correct boolean NOT NULL,
    selected_option_index integer NOT NULL,
    question_id bigint NOT NULL,
    submission_id bigint NOT NULL,
    ai_feedback text
);

ALTER TABLE public.questionnaire_submission_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questionnaire_submission_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.questionnaire_submissions (
    id bigint NOT NULL,
    score integer NOT NULL,
    student_id bigint NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    questionnaire_instance_id bigint NOT NULL,
    feedback_status character varying(20) DEFAULT 'NOT_REQUIRED'::character varying NOT NULL,
    CONSTRAINT questionnaire_submissions_feedback_status_check CHECK (((feedback_status)::text = ANY ((ARRAY['NOT_REQUIRED'::character varying, 'PENDING'::character varying, 'PROCESSING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.questionnaire_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questionnaire_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.questionnaires (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    grading_period_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    week_number integer NOT NULL,
    allowed_attempts integer NOT NULL,
    questions_per_attempt integer NOT NULL,
    target_student_id bigint,
    type character varying(255) DEFAULT 'NORMAL'::character varying NOT NULL,
    CONSTRAINT questionnaires_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT questionnaires_type_check CHECK (((type)::text = ANY ((ARRAY['NORMAL'::character varying, 'REMEDIAL'::character varying])::text[])))
);

ALTER TABLE public.questionnaires ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questionnaires_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.questions (
    id bigint NOT NULL,
    correct_option_index integer NOT NULL,
    is_remedial boolean NOT NULL,
    options text NOT NULL,
    text text NOT NULL,
    topic_id bigint NOT NULL,
    questionnaire_instance_id bigint NOT NULL,
    difficulty character varying(20),
    CONSTRAINT questions_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['LOW'::character varying, 'INTERMEDIATE'::character varying])::text[])))
);

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint
);

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.remedial_trackings (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_resolved boolean NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    weak_topic_id bigint NOT NULL,
    week_number integer NOT NULL,
    consolidation_mode boolean,
    difficulty character varying(20),
    last_remedial_score integer,
    required_question_count integer,
    CONSTRAINT remedial_trackings_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['LOW'::character varying, 'INTERMEDIATE'::character varying])::text[])))
);

ALTER TABLE public.remedial_trackings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.remedial_trackings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.role_permissions (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);

CREATE TABLE public.roles (
    id bigint NOT NULL,
    role_name character varying(255) NOT NULL
);

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sections (
    id bigint NOT NULL,
    education_level character varying(255) NOT NULL,
    grade_level character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT sections_education_level_check CHECK (((education_level)::text = 'SECONDARY'::text)),
    CONSTRAINT sections_grade_level_check CHECK (((grade_level)::text = 'SECOND'::text))
);

ALTER TABLE public.sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.study_plans (
    id bigint NOT NULL,
    education_level character varying(255) NOT NULL,
    grade_level character varying(255) NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT study_plans_education_level_check CHECK (((education_level)::text = 'SECONDARY'::text)),
    CONSTRAINT study_plans_grade_level_check CHECK (((grade_level)::text = 'SECOND'::text))
);

ALTER TABLE public.study_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.study_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.topics (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    order_index integer,
    course_id bigint NOT NULL,
    grading_period_id bigint NOT NULL
);

ALTER TABLE public.topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    is_temporary_password boolean DEFAULT true,
    last_password_change timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.academic_years
    ADD CONSTRAINT academic_years_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.achievement_insights
    ADD CONSTRAINT achievement_insights_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_background_tasks
    ADD CONSTRAINT ai_background_tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.areas
    ADD CONSTRAINT areas_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_sessions
    ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT classrooms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.document_targets
    ADD CONSTRAINT document_targets_pkey PRIMARY KEY (course_id, document_id, education_level, grade_level);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.grading_periods
    ADD CONSTRAINT grading_periods_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.onboarding_profiles
    ADD CONSTRAINT onboarding_profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.platform_tutorials
    ADD CONSTRAINT platform_tutorials_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.questionnaire_instances
    ADD CONSTRAINT questionnaire_instances_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.questionnaire_submission_answers
    ADD CONSTRAINT questionnaire_submission_answers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.questionnaire_submissions
    ADD CONSTRAINT questionnaire_submissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.questionnaires
    ADD CONSTRAINT questionnaires_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.remedial_trackings
    ADD CONSTRAINT remedial_trackings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.study_plans
    ADD CONSTRAINT study_plans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.study_plans
    ADD CONSTRAINT uk5ivvq8b2cj4vrp63jwr5rs17s UNIQUE (education_level, grade_level, course_id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT uk6nsvcecgwjnqbl29aa0vwd29r UNIQUE (user_id, classroom_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk716hgxp60ym1lifrdgp67xt5k UNIQUE (role_name);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk7tdcd6ab5wsgoudnvj7xf1b7l UNIQUE (user_id);

ALTER TABLE ONLY public.onboarding_profiles
    ADD CONSTRAINT uk971p7nh2x44cm6qimx2s2lpod UNIQUE (user_id);

ALTER TABLE ONLY public.ai_background_tasks
    ADD CONSTRAINT uk_ai_task_idempotency_key UNIQUE (idempotency_key);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT uk_document_checksum UNIQUE (file_checksum);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT uk_document_object_key UNIQUE (object_key);

ALTER TABLE ONLY public.questionnaire_submissions
    ADD CONSTRAINT uk_submission_instance_student UNIQUE (questionnaire_instance_id, student_id);

ALTER TABLE ONLY public.grading_periods
    ADD CONSTRAINT ukcelbu7wce27u2r9dxspc2tqyb UNIQUE (academic_year_id, bimester);

ALTER TABLE ONLY public.areas
    ADD CONSTRAINT ukejdunkx4j4ub0efqakfok81xd UNIQUE (coordinator_id);

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT ukf56yxln7yembif11f29ffo9h3 UNIQUE (education_level, grade_level, name);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT uknbpyjh9f4oh4fy14m4cpxrmjs UNIQUE (course_id, section_id, academic_year_id);

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT uknry1f3jmc4abb5yvkftlvn6vg UNIQUE (permission_name);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_ai_tasks_pending ON public.ai_background_tasks USING btree (task_type, status, available_at);

CREATE INDEX idx_chunks_content_tsv ON public.document_chunks USING gin (content_tsv);

CREATE INDEX idx_chunks_doc_chunk ON public.document_chunks USING btree (document_id, chunk_index);

CREATE INDEX idx_chunks_document ON public.document_chunks USING btree (document_id);

CREATE INDEX idx_documents_author ON public.documents USING btree (author_id);

CREATE INDEX idx_documents_status ON public.documents USING btree (status);

CREATE INDEX idx_documents_topic ON public.documents USING btree (topic_id);

CREATE INDEX idx_targets_lookup ON public.document_targets USING btree (education_level, grade_level, course_id);

CREATE INDEX idx_topics_course_order ON public.topics USING btree (course_id, order_index);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.questionnaire_submissions
    ADD CONSTRAINT fk2r45kpdjq18ltbdn9dbbfanvp FOREIGN KEY (questionnaire_instance_id) REFERENCES public.questionnaire_instances(id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fk3cpkdtwdxndrjhrx3gt9q5ux9 FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id);

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk5me5sdtbcnxj8bb5jxw72df44 FOREIGN KEY (classroom_id) REFERENCES public.classrooms(id);

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT fk6nlj52a6nmfu12oa5vn9kw9pm FOREIGN KEY (grading_period_id) REFERENCES public.grading_periods(id);

ALTER TABLE ONLY public.questionnaire_submission_answers
    ADD CONSTRAINT fk87fhjrydbl6e56efe4acfnhbh FOREIGN KEY (submission_id) REFERENCES public.questionnaire_submissions(id);

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT fka919165pe8mqragt20o7nxyu3 FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id) REFERENCES public.permissions(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT fkhn8u5k2hlwgftn6xkk7i2vh1o FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.study_plans
    ADD CONSTRAINT fkhrr7f13qa8bk9j9vetjl9hjfo FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT fki317vco72foddhahlhnfcgn5b FOREIGN KEY (section_id) REFERENCES public.sections(id);

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkibaio78b1ivinrbsck1g8o3py FOREIGN KEY (questionnaire_instance_id) REFERENCES public.questionnaire_instances(id);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fkkci2j24y6xvscsijbrjebwsv FOREIGN KEY (area_id) REFERENCES public.areas(id);

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT fkks8knsiau23lcmv9mydqjmj84 FOREIGN KEY (document_id) REFERENCES public.documents(id);

ALTER TABLE ONLY public.questionnaire_submission_answers
    ADD CONSTRAINT fkljk220k8g5rmnreeq8dx1dfyr FOREIGN KEY (question_id) REFERENCES public.questions(id);

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.questionnaire_instances
    ADD CONSTRAINT fkoc1c56b1qv9n3uycbrmgs54jp FOREIGN KEY (questionnaire_id) REFERENCES public.questionnaires(id);

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT fkptrcjflhvj48duhcag4f3x9j0 FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.document_targets
    ADD CONSTRAINT fkro3w2xsqxs9svxa7j4h68j7sm FOREIGN KEY (document_id) REFERENCES public.documents(id);

ALTER TABLE ONLY public.grading_periods
    ADD CONSTRAINT fksgaav5i1ftespenqfa664wff3 FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);
